In [1]:
import matplotlib.pyplot as plt
import numpy as np
from import_fun import matrix_to_sparse, sparse_to_matrix
from numba import njit, prange

In [2]:
N_pre, N_post = 3, 4
conn1 = np.array([[0, 1, 0, 0],
                  [1, 0, 1, 0],
                  [0, 1, 0, 1],
                  [0, 1, 0, 0]])

conn = np.array([[0, 1, 0],
                  [1, 0, 1],
                  [0, 1, 0],
                  [0, 1, 0]])

w = np.random.rand(4, 3)

In [3]:
conn
w

array([[0.42380067, 0.05832541, 0.48829076],
       [0.85036368, 0.91041286, 0.14187141],
       [0.06011118, 0.85094866, 0.98778653],
       [0.60977771, 0.1973929 , 0.94843322]])

In [4]:
pre_ids, post_ids, weights = matrix_to_sparse(conn, w)

In [5]:
mem1 = np.random.rand(3)
mem2 = np.random.rand(4)
mem1, mem2

(array([0.01565417, 0.44067736, 0.64623452]),
 array([0.40279449, 0.56976639, 0.95293663, 0.96609922]))

In [6]:
print(pre_ids, "\n", post_ids, "\n", weights)

[1 0 2 1 1] 
 [0 1 1 2 3] 
 [ 5.83254079e-002  9.10412860e-001  6.01111800e-002  6.09777713e-001
 -3.81257193e-270]


In [7]:
weights*(mem1[pre_ids] - mem2[post_ids])

array([ 2.20953375e-003, -5.04470899e-001,  4.59658923e-003,
       -3.12364284e-001,  2.00320865e-270])

In [8]:
conn, w = sparse_to_matrix(N_pre, N_post, pre_ids, post_ids, weights)

conn, w

(array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0],
        [0, 1, 0]], dtype=int32),
 array([[ 0.00000000e+000,  5.83254079e-002,  0.00000000e+000],
        [ 9.10412860e-001,  0.00000000e+000,  6.01111800e-002],
        [ 0.00000000e+000,  6.09777713e-001,  0.00000000e+000],
        [ 0.00000000e+000, -3.81257193e-270,  0.00000000e+000]]))